/*
 * admin.js — the admin role and the exam catalogue.
 *
 * Admin is a Firestore document, not a custom claim: claims require the Admin
 * SDK and therefore a backend, and this app deliberately has none. Existence of
 * `admins/{uid}` IS the role, and no client can create one — it is granted by
 * hand in the Firebase console.
 *
 * The catalogue decides what students see. exams/index.json says what EXISTS
 * (it is generated by the pipeline); `catalog/{examId}.published` says what is
 * visible. A missing catalogue document counts as published, so an exam added
 * by `python sync.py` appears rather than silently vanishing — unpublishing is
 * the deliberate act, not publishing.
 *
 * ⚠️ VISIBILITY, NOT ACCESS CONTROL. Unpublishing removes an exam from the
 * menu. It does not make it unreachable: the exam JSON is a static file on
 * GitHub Pages, so anyone who knows the URL can still fetch
 * exams/<id>/<id>.json directly. Real access control needs a server that can
 * refuse the request, and this app deliberately has none. Treat the catalogue
 * as "not ready for students yet", never as "secret".
 */

import {
  collection, doc, getDoc, getDocs, setDoc, serverTimestamp,
} from "https://www.gstatic.com/firebasejs/12.9.0/firebase-firestore.js";

import { auth, db } from "./firebase.js?v=48124d24";

let adminCache = null;

/** Is the signed-in user an admin? Cheap, cached, and safe to call often. */
export async function isAdmin() {
  if (adminCache !== null) return adminCache;
  const user = auth.currentUser;
  if (!user) return (adminCache = false);
  try {
    const snap = await getDoc(doc(db, "admins", user.uid));
    adminCache = snap.exists();
  } catch {
    // Rules deny reading someone else's admin doc; a denial simply means "no".
    adminCache = false;
  }
  return adminCache;
}

/** examId -> { published }. Missing entries mean published. */
export async function loadCatalog() {
  const map = {};
  try {
    const snap = await getDocs(collection(db, "catalog"));
    snap.forEach(d => { map[d.id] = d.data(); });
  } catch (err) {
    // A student who cannot read the catalogue should still get their exams,
    // rather than an empty screen.
    console.warn("Nie udało się wczytać katalogu:", err.code || err.message);
  }
  return map;
}

export function isPublished(catalog, examId) {
  const entry = catalog[examId];
  return entry ? entry.published !== false : true;
}

async function setPublished(examId, published) {
  await setDoc(doc(db, "catalog", examId), {
    published,
    updatedAt: serverTimestamp(),
    updatedBy: auth.currentUser?.uid || null,
  }, { merge: true });
}

/* ------------------------------------------------------------------ *
 * Panel
 * ------------------------------------------------------------------ */

/**
 * Render the admin panel under the exam menu. No-op for everyone else, so it
 * is safe to call unconditionally.
 *
 * `onChange` re-renders the student-facing menu after a toggle.
 */
export async function mountAdminPanel(examIndex, catalog, describeExam, onChange) {
  if (!(await isAdmin())) return;

  let box = document.getElementById("admin-panel");
  if (!box) {
    box = document.createElement("div");
    box.id = "admin-panel";
    box.className = "mt-12";
    document.getElementById("view-menu").appendChild(box);
  }

  const rows = examIndex.map(entry => {
    const { level, when } = describeExam(entry.id);
    const on = isPublished(catalog, entry.id);
    return `
      <div class="flex items-center gap-4 px-6 py-3" data-exam="${entry.id}">
        <div class="flex-grow min-w-0">
          <div class="font-semibold text-slate-800 text-sm">Matura ${when} — ${level}</div>
          <div class="text-xs text-slate-400 font-mono">${entry.id}</div>
        </div>
        <span class="text-xs font-medium ${on ? "text-green-600" : "text-slate-400"}" data-state>
          ${on ? "widoczny" : "ukryty"}
        </span>
        <button type="button" data-toggle
          class="text-xs font-semibold px-3 py-1.5 rounded-lg border transition-colors
                 ${on ? "border-slate-200 text-slate-600 hover:bg-slate-50"
                      : "border-indigo-200 bg-indigo-50 text-indigo-700 hover:bg-indigo-100"}">
          ${on ? "Ukryj" : "Opublikuj"}
        </button>
      </div>`;
  }).join("");

  box.innerHTML = `
    <div class="flex items-center gap-2 mb-4">
      <span class="material-symbols-outlined text-slate-400">admin_panel_settings</span>
      <h3 class="text-lg font-bold text-slate-800">Panel administratora</h3>
    </div>
    <div class="bg-white rounded-2xl border border-slate-200 shadow-sm divide-y divide-slate-100">
      ${rows}
    </div>
    <p class="text-xs text-slate-400 mt-3">
      Arkusz ukryty nie pojawia się uczniom. Nowy arkusz dodany przez
      <code>sync.py</code> jest domyślnie widoczny.
    </p>`;

  box.querySelectorAll("[data-toggle]").forEach(btn => {
    btn.addEventListener("click", async () => {
      const row = btn.closest("[data-exam]");
      const examId = row.dataset.exam;
      const next = !isPublished(catalog, examId);

      btn.disabled = true;
      try {
        await setPublished(examId, next);
        catalog[examId] = { ...(catalog[examId] || {}), published: next };
        await mountAdminPanel(examIndex, catalog, describeExam, onChange);
        onChange();
      } catch (err) {
        row.querySelector("[data-state]").textContent = "błąd zapisu";
        console.warn("Nie udało się zmienić widoczności:", err.code || err.message);
      } finally {
        btn.disabled = false;
      }
    });
  });
}
